Feature/編輯按鈕功能
c711cat/lemon_coffee pull request #15
Opened 2021-10-26 10:55 UTC by c711cat

## 在管理者頁面按下某產品的編輯按鈕，跳轉至該產品的編輯頁面
### 1. 在 mockoon 建立按下編輯按鈕後，可以取得即將編輯的 " 假設產品資料 "
### 2. 跳轉的頁面路由會代入該產品 id 
### 3. 編輯頁面會藉由從 mockoon 取得的假設資料 ，自動對應代入到每個 input 中
### ★ 示意圖 : 
![image](https://user-images.githubusercontent.com/77562017/138863896-e8246ea7-66fe-4e5a-8811-4f898a4cf039.png)

![image](https://user-images.githubusercontent.com/77562017/138863978-c50da1ea-41bd-4f6f-8c5b-81e8d0bef4db.png)

2021-11-02 13:32 UTC, kakas commented on src/components/AddProduct.vue
> +          console.log(response);
console 砍一下

2021-11-02 13:32 UTC, kakas commented on src/components/AddProduct.vue
> +    this.editProduct();
這邊有點奇妙，會讓人看不懂為什麼 created 之後要馬上呼叫 editProduct
建議
- 把「新增」跟「編輯」寫成兩個 view
- 把 form 寫成一個 component

e.g.

new 的 view
```vue
<template>
  <ProductForm product="product"></ProductForm>
</template>

export default {
  data() {
    return {
      product: { ... },
    };
  },
  methods: {
    createProduct() {
      // 送到後端新增一筆 product
    },
  },
};

```

edit 的 view

```vue
<template>
  <ProductForm product="product"></ProductForm>
</template>

export default {
  data() {
    return {
      product: { ... },
    };
  },
  methods: {
    getProduct() {
      // 拿要編輯的 product 資料
    },
    updateProduct() {
      // 送到後端更新 product 資料
    }
  },
};
```

2021-11-02 13:32 UTC, kakas commented on src/components/CleanBeanList.vue
> +      this.$router.push(`/admin/products/edit/${item.id}`);
cool

2021-11-03 08:03 UTC, c711cat commented on src/components/AddProduct.vue
> +          console.log(response);
好~  https://github.com/c711cat/lemon_coffee/pull/15/commits/67e8b7f566d905b49de870235e3c600281a505fe

2021-11-03 08:03 UTC, c711cat commented on src/components/AddProduct.vue
> +    this.editProduct();
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/67e8b7f566d905b49de870235e3c600281a505fe

2021-11-08 10:20 UTC, kakas commented
(BUG) 按編輯後，產品資料沒有帶過去編輯的表單

2021-11-08 10:48 UTC, kakas requested changes

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/EditProduct.vue
> +      axios.post(api, { products: this.product }).then((response) => {
http verb 應該是 put

```suggestion
      axios.put(api, { product: this.product }).then((response) => {
```

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/EditProduct.vue
> +      const api = `${process.env.VUE_APP_API}/admin/products`;
```suggestion
      const api = `${process.env.VUE_APP_API}/admin/products/${product.id}`;
```

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/EditProduct.vue
> +    this.id = this.$route.params.productId;
因為 id 不會被修改也不應該被修改，所以這個資料不要存到 data 裡面比較好
在需要的地方直接拿出來用就好了，或是可以寫到 computed 裡面

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/EditProduct.vue
> +      const api = `${process.env.VUE_APP_API}/admin/products/edit/${this.id}`;
抱歉跟你講錯 API 了，應該是
```suggestion
      const api = `${process.env.VUE_APP_API}/admin/products/${this.id}/edit`;
```

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/EditProduct.vue
> +      this.$router.push("/admin");
順序應該是
axios.put -> get response -> 回 admin 首頁

現在是還沒等到 response 回來就回 admin 首頁了

2021-11-08 10:48 UTC, kakas commented on src/components/ProductForm.vue
>      },
good

2021-11-08 10:48 UTC, kakas commented on src/components/ProductForm.vue
> +      >
Nice 大概有樣子了。

不過這邊可以在稍微改一下，看起來會更簡潔

src/views/Manager/AddProduct.vue
```vue
<ProductForm :editItem="product" onSubmit="addProduct"></ProductForm>
```

src/views/Manager/EditProduct.vue
```vue
<ProductForm :editItem="product" onSubmit="updateProduct"></ProductForm>
```

src/components/ProductForm.vue
```vue
<button class="ui primary button" @click.prevent="onSubmit">送出</button>
```

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/AddProduct.vue
> +      this.$router.push("/admin");
還沒等到 response 回來就切換頁面了

2021-11-08 10:48 UTC, kakas commented on src/views/Manager/AddProduct.vue
> +      axios.post(api, { products: this.product }).then((response) => {
不好意思跟你講錯了，這邊應該是
```suggestion
      axios.post(api, { product: this.product }).then((response) => {
```

2021-11-10 07:01 UTC, c711cat commented on src/views/Manager/EditProduct.vue
> +      axios.post(api, { products: this.product }).then((response) => {
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:01 UTC, c711cat commented on src/views/Manager/EditProduct.vue
> +      const api = `${process.env.VUE_APP_API}/admin/products`;
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:01 UTC, c711cat commented on src/views/Manager/EditProduct.vue
> +    this.id = this.$route.params.productId;
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:01 UTC, c711cat commented on src/views/Manager/EditProduct.vue
> +      const api = `${process.env.VUE_APP_API}/admin/products/edit/${this.id}`;
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:01 UTC, c711cat commented on src/views/Manager/EditProduct.vue
> +      this.$router.push("/admin");
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:02 UTC, c711cat commented on src/components/ProductForm.vue
> +      >
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:02 UTC, c711cat commented on src/views/Manager/AddProduct.vue
> +      this.$router.push("/admin");
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:02 UTC, c711cat commented on src/views/Manager/AddProduct.vue
> +      axios.post(api, { products: this.product }).then((response) => {
改好了~  https://github.com/c711cat/lemon_coffee/pull/15/commits/3b9382398d7a2e9ec05e8a03038f1baa33efab43

2021-11-10 07:12 UTC, kakas commented on src/views/Manager/AddProduct.vue
> +  <ProductForm @add="addProduct" :onSubmit="addProduct"></ProductForm>
`@add` 應該沒用到了？

2021-11-10 07:12 UTC, kakas commented on src/views/Manager/EditProduct.vue
> +          this.getProduct();
為什麼需要這一行？

2021-11-10 07:15 UTC, c711cat commented on src/views/Manager/AddProduct.vue
> +  <ProductForm @add="addProduct" :onSubmit="addProduct"></ProductForm>
好了  https://github.com/c711cat/lemon_coffee/pull/15/commits/2027d7e3d213b92f9de286fd823b0041c11bbc15

2021-11-10 07:16 UTC, c711cat commented on src/views/Manager/EditProduct.vue
> +          this.getProduct();
改好了  https://github.com/c711cat/lemon_coffee/pull/15/commits/6099e36c3736d1c3af7ae108eadd2f2730f4f65d

2021-11-10 07:18 UTC, kakas approved these changes

2021-11-10 07:18 UTC, merged