Feature/註冊 及 登入的功能
c711cat/lemon_coffee pull request #26
Opened 2021-12-02 07:39 UTC by c711cat

## ★ 註冊功能 ( router : /entrance/register )
### 1. 註冊成功 及 失敗 會出現對應的吐司訊息 ( 不想一直註冊新帳號，所以沒有拍成功的圖片 )
### 2. 若註冊成功後，會跳到登入頁面
![image](https://user-images.githubusercontent.com/77562017/144377857-fb68ef39-aa76-4b31-b962-f3682170d6cd.png)

## ★ 登入功能 ( router : /entrance/login )
### 1. 登入成功後，出現成功吐司訊息，並跳轉到全部豆單頁面
![image](https://user-images.githubusercontent.com/77562017/144378113-83b866c9-1e65-4443-92af-56c56a6c470c.png)

### 2. 登入成功後 navbar 的登入/註冊字眼消失，改成一個人像的 icon
![image](https://user-images.githubusercontent.com/77562017/144378161-c772438f-0875-40bf-99a2-7ee9345ffb6b.png)

### 3. 若登入失敗，出現相對應吐司訊息，不跳轉頁面
![image](https://user-images.githubusercontent.com/77562017/144378217-9166f60c-6c82-4df9-96c8-5ac03dc634a1.png)

2021-12-04 05:01 UTC, kakas commented on src/components/Login.vue
> +      login_data: {
感覺不用 login_data 這一層？
資料越多層處理起來會越複雜

2021-12-04 05:11 UTC, kakas requested changes
不能打兩次註冊 API

2021-12-04 05:11 UTC, kakas commented on src/components/Login.vue
>  export default {
```suggestion
import axios from "axios";

export default {
```

2021-12-04 05:11 UTC, kakas commented on src/components/Login.vue
> +      axios.post(api, this.login_data).catch((error) => {
這樣寫會發兩次 request，只要發一次 request 就好了

```js
      axios
        .post(api, this.login_data)
        .then(() => {
          this.$toast.add({
            severity: "success",
            summary: "登入成功",
            life: 2000,
          });
          this.emitter.emit("refreshIdentity");
          this.$router.push("/beanlist");
        })
        .catch(() => {
          this.$toast.add({
            severity: "error",
            summary: "登入失敗",
            life: 2000,
          });
        });
```

2021-12-04 05:11 UTC, kakas commented on src/components/Navbar.vue
> +            v-if="!member"
寫一個 computed `is_login` 比較好讀
`v-if="!is_login"`

另外 v-if 寫在 `router-link` 上感覺比較合理，因為是用有無登入決定顯示哪個 link

2021-12-04 05:11 UTC, kakas commented on src/components/Register.vue
> +    register() {
裡面打了兩次 API，但其實只需要打一次就好

2021-12-07 03:05 UTC, c711cat commented on src/components/Login.vue
> +      login_data: {
改好了~  https://github.com/c711cat/lemon_coffee/pull/26/commits/34646483f4fe064ef15e8bb6046f2107712ab91a

2021-12-07 03:05 UTC, c711cat commented on src/components/Login.vue
>  export default {
改好了~~  https://github.com/c711cat/lemon_coffee/pull/26/commits/75b1a87712f246281463aa76fb81ee526d0bb949

2021-12-07 03:06 UTC, c711cat commented on src/components/Login.vue
> +      axios.post(api, this.login_data).catch((error) => {
改好了~   https://github.com/c711cat/lemon_coffee/pull/26/commits/b406fdc672cd26b6950ea699a38bfb874034c6ca

2021-12-07 03:08 UTC, c711cat commented on src/components/Register.vue
> +    register() {
改好了~~  https://github.com/c711cat/lemon_coffee/pull/26/commits/9019506d76613fc87f711d4548191bbffb61e2c7

2021-12-07 12:44 UTC, kakas commented on src/components/Register.vue
> +        .catch(() => {
```suggestion
        .catch(() => {
```

2021-12-07 12:45 UTC, kakas commented on src/components/Register.vue
> +        .catch(() => {
.catch 要跟上面的連在一起
（上面那一行空白刪掉唄

2021-12-07 12:49 UTC, c711cat commented on src/components/Register.vue
> +        .catch(() => {
好了~   https://github.com/c711cat/lemon_coffee/pull/26/commits/0ed40a3073bbd0a7a73d10c50a24c0e9b90a581c

2021-12-07 12:50 UTC, kakas approved these changes

2021-12-07 12:50 UTC, merged