Feature/ 按「下訂單」按鈕串接建立訂單 API ( create order )
c711cat/lemon_coffee pull request #42
Opened 2022-01-03 08:49 UTC by c711cat

https://kakas-redmine.herokuapp.com/issues/981
###  ★  在 /checkout 頁面，按下「下訂單」按鈕，連結到 /order/:id
![image](https://user-images.githubusercontent.com/77562017/147912749-6e6616e3-5f8d-4a41-b093-c5620c3bf886.png)

###  ★ 訂單頁面  :    /order/:id
![image](https://user-images.githubusercontent.com/77562017/147912233-69db8196-2d27-4e73-961c-cca30ea1ff8e.png)

2022-01-07 10:15 UTC, kakas commented
按下「查看購物車後」會噴錯
![image](https://user-images.githubusercontent.com/1676957/148528989-61949989-5c1d-4fdf-bbef-99f548251533.png)

2022-01-07 10:20 UTC, kakas requested changes

2022-01-07 10:20 UTC, kakas commented on src/components/AddresseeForm.vue
> +            v-model="buyer.shipping_info.payment_method"
buyer 這一層感覺有點多餘，可以把它拿掉嘛？

2022-01-07 10:20 UTC, kakas commented on src/components/CartSidebar.vue
> +      @click.prevent="$emit('close-visible')"
close-visible 是用來幹嘛的？
感覺可以換一個比較易懂的名字

2022-01-07 10:20 UTC, kakas commented on src/components/Checkout.vue
> +          <div class="p-col-8 p-lg-10">{{ buyer.shipping_info.name }}</div>
覺得可以把 buyer 這一層拿掉

2022-01-07 10:20 UTC, kakas commented on src/components/Checkout.vue
> +      const data = { order: JSON.parse(JSON.stringify(this.buyer)) };
為什麼需要 JSON.stringify 然後又 JSON.parse？

2022-01-07 10:20 UTC, kakas commented on src/components/Checkout.vue
> +        data.order.shipping_info.shipping_method = "home_delivery";
shipping_method 顯示的時候利用 computed 轉換成中文
資料用英文 (home_delivery) 儲存會比較好

2022-01-07 10:20 UTC, kakas commented on src/components/Order.vue
> +<template>
等錯誤修好了我再繼續 review

2022-01-08 07:43 UTC, kakas commented on src/components/Order.vue
> +      }
這邊可以用 switch 寫，順便練習一下 switch 語法

2022-01-08 07:43 UTC, kakas commented on src/components/Order.vue
> +      }
這邊可以用 switch 寫，順便練習一下 switch 語法

      switch (status) {
        case "pending":
          return "處理中";
        case "confirmed":
          return "已確認";
        case "finished":
          return "已完成";
        case "canceled":
          return "已取消";
      }

2022-01-08 07:43 UTC, kakas commented on src/components/Order.vue
> +      }
這邊可以用 switch 寫，順便練習一下 switch 語法

2022-01-08 07:43 UTC, kakas commented on src/components/Order.vue
> +      }
這邊可以用 switch 寫，順便練習一下 switch 語法

2022-01-17 02:01 UTC, c711cat commented
> 按下「查看購物車後」會噴錯 ![image](https://user-images.githubusercontent.com/1676957/148528989-61949989-5c1d-4fdf-bbef-99f548251533.png)

我這裡看沒有問題
不過後續的 PR 我有多做一個功能 :  " 購物車空的時不會出現其他按鈕 UI "

2022-01-17 06:09 UTC, c711cat commented on src/components/AddresseeForm.vue
> +            v-model="buyer.shipping_info.payment_method"
拿掉了~
https://github.com/c711cat/lemon_coffee/pull/42/commits/830ae0d01b9811f81748375c028b735e02d78936

2022-01-17 06:09 UTC, c711cat commented on src/components/Checkout.vue
> +          <div class="p-col-8 p-lg-10">{{ buyer.shipping_info.name }}</div>
也拿掉了
https://github.com/c711cat/lemon_coffee/pull/42/commits/2913e3adc810a9ba113e53b2a5b0e07df4789b4a

2022-01-17 06:22 UTC, c711cat commented on src/components/Checkout.vue
> +      const data = { order: JSON.parse(JSON.stringify(this.buyer)) };
我寫到頭暈了...
改好了~
https://github.com/c711cat/lemon_coffee/pull/42/commits/87ef46883b5d70c7705402c296cbea361d5e280a

2022-01-17 08:14 UTC, c711cat commented on src/components/CartSidebar.vue
> +      @click.prevent="$emit('close-visible')"
改好了  https://github.com/c711cat/lemon_coffee/pull/42/commits/f7b622b4d5ba616829b5b014e5ed81584dcb0a44

2022-01-17 09:06 UTC, c711cat commented on src/components/Checkout.vue
> +      const data = { order: JSON.parse(JSON.stringify(this.buyer)) };
我想起來了!
### 在購物車中沒有商品時，按下 下訂單 的按鈕
![image](https://user-images.githubusercontent.com/77562017/149738268-f4d65de7-cc52-4540-b3ff-a56e7ad82636.png)
### 雖然不會跳轉頁面，也有吐司訊息出現，但是送貨方式會變成英文
![image](https://user-images.githubusercontent.com/77562017/149738404-87133f05-5691-4597-828e-6a750d212364.png)
### 若改用深層拷貝就不會變成英文
不過之後我有讓側邊購物車在沒有加入商品時，不會出現按鈕可以按，就不會點到 /checkout 頁面，也較不會在沒有商品時去點下訂單的按鈕了，除非自行輸入網址
![image](https://user-images.githubusercontent.com/77562017/149739340-b1efb4ae-32c2-40c4-a3ba-7c874fc78b8f.png)

2022-01-18 03:08 UTC, c711cat commented on src/components/Checkout.vue
> +        data.order.shipping_info.shipping_method = "home_delivery";
改好了~ https://github.com/c711cat/lemon_coffee/pull/42/commits/bc40744941f68e2558b6f03e67c52556c0dbb015

2022-01-18 03:08 UTC, c711cat commented on src/components/Checkout.vue
> +      const data = { order: JSON.parse(JSON.stringify(this.buyer)) };
改這樣就不用深層拷貝了，我又改回來了。https://github.com/c711cat/lemon_coffee/pull/42/commits/bc40744941f68e2558b6f03e67c52556c0dbb015

2022-01-18 03:32 UTC, c711cat commented on src/components/Order.vue
> +      }
改好了~   https://github.com/c711cat/lemon_coffee/pull/42/commits/38730bba80977b4831cf1c44835049b23fbcae25

2022-01-18 05:31 UTC, c711cat commented on src/components/Order.vue
> +      }
改好了~  https://github.com/c711cat/lemon_coffee/pull/42/commits/e03eb121728f0f2ac393626dbacfd381ba8a58f6

2022-01-18 05:35 UTC, c711cat commented on src/components/Order.vue
> +      }
改好了~  https://github.com/c711cat/lemon_coffee/pull/42/commits/5a81cebf24e6debbc2a77e98a93c4d9143fad890

2022-01-18 05:38 UTC, c711cat commented on src/components/Order.vue
> +      }
改好了~  https://github.com/c711cat/lemon_coffee/pull/42/commits/6e6fa6cf4983a52ff27f9e62425f398cabd352e9

2022-01-20 10:44 UTC, kakas reviewed
再改一下唄

2022-01-20 10:44 UTC, kakas commented on src/components/AddresseeForm.vue
> +          v-if="shipping_info.shipping_method === '宅配'"
這邊可以寫一個 method 或 computed 來做判斷

`v-if="isHomeDelivery"`

2022-01-20 10:44 UTC, kakas commented on src/components/AddresseeForm.vue
> +        ).shipping_info;
```suggestion
        const personalData = JSON.parse(localStorage.getItem("personalData"));
        this.note = personalData.note;
        this.shipping_info = personalData.shipping_info;
```

2022-01-20 10:44 UTC, kakas commented on src/components/AddresseeForm.vue
> +          />
> shipping_method 顯示的時候利用 computed 轉換成中文
資料用英文 (home_delivery) 儲存會比較好

我的意思是這樣：


```vue
    <Dropdown
      v-model="shipping_info.payment_method"
      :options="payment_methods"
      optionLabel="label"
      optionValue="value"
    />


  data() {
    return {
      payment_methods: [{ label: "貨到付款", value: "home_delivery" }],
    };
  },
```

2022-01-20 10:44 UTC, kakas commented on src/components/AddresseeForm.vue
> +          />
optionLabel 是要用哪個顯示
optionValue 是 value

2022-01-20 10:44 UTC, kakas commented on src/components/AddresseeForm.vue
> +          />
shipping_method 也是這樣改

2022-01-20 10:44 UTC, kakas commented on src/components/Checkout.vue
> +    },
Nice!

2022-01-20 10:44 UTC, kakas commented on src/components/Checkout.vue
> +            v-if="shipping_info.shipping_method === '宅配'"
這邊可以寫一個 method 或 computed 來做判斷

v-if="isHomeDelivery"

2022-01-20 10:44 UTC, kakas commented on src/components/Checkout.vue
> +            v-if="shipping_info.shipping_method === '宅配'"
這邊可以寫一個 method 或 computed 來做判斷

v-if="isHomeDelivery"

2022-01-20 10:44 UTC, kakas commented on src/components/Checkout.vue
> +            );
應該是這樣才對？

```suggestion
            const buyerRecord = JSON.parse(localStorage.getItem("personalData")) || {};
```

因為 `JSON.parse({})` 會壞掉

2022-01-20 10:44 UTC, kakas commented on src/components/Order.vue
> +        case "outstanding" || "unpaid":
不能用 `||` 要寫成
case "outstanding":
case "unpaid":
  return "未付款";

2022-01-21 03:14 UTC, c711cat commented on src/components/AddresseeForm.vue
> +          v-if="shipping_info.shipping_method === '宅配'"
改好了~  https://github.com/c711cat/lemon_coffee/pull/42/commits/e76f34ce11cdcbdc310e92e940b4d005afb4f87d

2022-01-21 06:40 UTC, c711cat commented on src/components/AddresseeForm.vue
> +          />
改好了~  https://github.com/c711cat/lemon_coffee/pull/42/commits/7ea73fec170df91b34aaab8a21c3c9737bd34193

2022-01-21 06:41 UTC, c711cat commented on src/components/AddresseeForm.vue
> +        ).shipping_info;
改好了~  https://github.com/c711cat/lemon_coffee/pull/42/commits/7ea73fec170df91b34aaab8a21c3c9737bd34193

2022-01-21 06:56 UTC, c711cat commented on src/components/Checkout.vue
> +            v-if="shipping_info.shipping_method === '宅配'"
改好了  https://github.com/c711cat/lemon_coffee/pull/42/commits/c7c4bda37bae41a31770667f5428981f5e29658c

2022-01-21 06:57 UTC, c711cat commented on src/components/Checkout.vue
> +            v-if="shipping_info.shipping_method === '宅配'"
改好了  https://github.com/c711cat/lemon_coffee/pull/42/commits/c7c4bda37bae41a31770667f5428981f5e29658c

2022-01-21 06:58 UTC, c711cat commented on src/components/Checkout.vue
> +            );
改好了~　https://github.com/c711cat/lemon_coffee/pull/42/commits/6d75318a0968df64974228fbb6bce633c612a991

2022-01-21 07:00 UTC, c711cat commented on src/components/Order.vue
> +        case "outstanding" || "unpaid":
改好了～　　https://github.com/c711cat/lemon_coffee/pull/42/commits/6d75318a0968df64974228fbb6bce633c612a991

2022-01-21 07:01 UTC, c711cat commented on src/components/Order.vue
> +        case "outstanding" || "unpaid":
改好了～　https://github.com/c711cat/lemon_coffee/pull/42/commits/5cc9452bbbabcb1fca5e3cd72e1d814a1b3f7e3a

2022-01-21 07:35 UTC, kakas approved these changes

2022-01-21 07:35 UTC, merged