Feature/ 顯示運費及其他價錢明細在 /cart 、/checkout 及 /order/:id 頁面 ( shipping amount )
c711cat/lemon_coffee pull request #54
Opened 2022-01-29 08:49 UTC by c711cat

https://kakas-redmine.herokuapp.com/issues/933
### 總付款金額計算方式 : 
### 1. 小計 - 小於 1000 元 : 運費 100元
### 2. 小計 - 大於等於 1000 元，出現滿千免運明細
### 3. 總付款金額 - 在前端會自動計算是否含運費
### ★ 在側欄小購物，按下「查看購物車」按鈕，會前往 /cart 頁面
![image](https://user-images.githubusercontent.com/77562017/151653949-a603ea87-f225-4295-826e-fbc4dd23575f.png)
### ★ 手機版
![image](https://user-images.githubusercontent.com/77562017/151654483-2e835ddd-0e88-4581-a61e-5163e5b45e45.png)

### ★ 按下「去買單」按鈕，會前往 /checkout 頁面
![image](https://user-images.githubusercontent.com/77562017/151654364-4b2cc4f3-fa47-4e99-b8a5-708ee33139e2.png)
### ★ 手機版
![image](https://user-images.githubusercontent.com/77562017/151654496-da5d969a-3d69-4762-b87f-ef40e967ff51.png)

### ★ 按下「下訂單」按鈕，會前往 /order/:id 頁面
![image](https://user-images.githubusercontent.com/77562017/151654428-9035f8e3-4cfc-490b-ac55-765101fde887.png)
### ★ 手機版
![image](https://user-images.githubusercontent.com/77562017/151654445-43fed8dc-50be-4310-9f03-9ff9f66e3cb6.png)

2022-02-13 06:21 UTC, kakas commented
滿千免運這個功能還不賴。
不過因為票上沒有說要做「滿千免運」的功能，所以建議以後只做票上描述的功能就好
其他的功能討論過再做比較好。
不然就會出現前端有滿千免運，但後端卻沒有的問題。
在實際使用上可能會因為後端沒有記錄到這件事情，造成消費糾紛。

2022-02-13 08:52 UTC, kakas requested changes

2022-02-13 08:52 UTC, kakas commented on src/components/Cart.vue
> +    shipping_fee() {
可以把「滿千免運」的邏輯放到這裡面來計算運費

2022-02-13 08:52 UTC, kakas commented on src/components/Cart.vue
> +    shipping_fee() {
然後 free_shipping 裡面可以改成
`return this.shipping_fee == 0`

2022-02-13 08:52 UTC, kakas commented on src/components/Cart.vue
> +      };
這四個值應該都可以算出來？
如果可以計算出來就不要傳的（如果覺得程式碼很重複以後再優化就好）
另外是資料放在網址會讓買的人很容易隨便去改資料

2022-02-13 08:52 UTC, kakas commented on src/components/AddresseeForm.vue
> -<template>
這個元件為什麼要砍掉？
有什麼功能做不出來嗎？

2022-02-13 08:52 UTC, kakas commented on src/components/Checkout.vue
> +            v-if="price_details.free_shipping === 'true'"
price_details.free_shipping 應該不是字串？

```suggestion
            v-if="price_details.free_shipping === true"
```

2022-02-14 04:30 UTC, kakas commented on src/components/Cart.vue
> +    shipping_fee() {
這樣呢？

```js
free_shipping() {
  return shippingFee === 0
}

originShippingFee() { 
  switch(this.shipping_info.shipping_method) {
    case 'home_delivery':
      return 100;
    default:
      return 0;
  }
}

shippingFee() {
  if (free_shipping) {
    return 0
  } else {
    return this.originShippingFee
  }
}
```

2022-02-14 05:40 UTC, c711cat commented on src/components/Cart.vue
> +    shipping_fee() {
那顯示的 UI 方式要更改嗎?
滿千免運改成 0 不是 -100 ?
我想知道需要改成什麼顯示規則

2022-02-14 05:44 UTC, c711cat commented on src/components/Cart.vue
> +    shipping_fee() {
一開始預訂的 顯示規則 : 
1. 未滿 1000  的情形 :
    小計 500
    運費 100
    總計 600

2.滿 1000 情形 :
    小計        1000
    運費          100
    滿千免運 -100
    總計        1000
問題 : 現在希望的 顯示規則 ?

2022-02-14 05:46 UTC, kakas commented on src/components/Cart.vue
> +    shipping_fee() {
照原本的顯示規則就可以了

2022-02-14 05:49 UTC, kakas commented on src/components/Cart.vue
> +    shipping_fee() {
![image](https://user-images.githubusercontent.com/1676957/153807305-19a3286b-1520-4fd0-b51d-91ea7a0c2022.png)

2022-02-14 05:51 UTC, c711cat commented on src/components/AddresseeForm.vue
> -<template>
當初不想一直重新計算小計、運費、滿千免運及總金額，
所以希望可以由 /Cart 傳已經算好的資料到下一頁 /Checkout，
但是不同頁面的跨元件傳遞資料，我越寫越複雜...
索性就把收件人資料的 Form 元件刪除，直接放到 Cart 元件中。

但是上一則你有提到重複的程式碼可以之後再優化，也不建議從網址傳遞資料，
那我再把收件人的 Form 元件改回去，
再重新計算 : 小計、運費、滿千免運及總金額。

2022-02-14 06:03 UTC, c711cat commented on src/components/Cart.vue
> +    shipping_fee() {
### ★ 蝦皮的顯示方式 : 把運費寫出來，達免運資格再列一行扣掉
![image](https://user-images.githubusercontent.com/77562017/153808454-299f2cbf-6205-4ab4-aa40-7a2d6f61faf9.png)
### ★ 步昂的顯示方式 : 達免運資格，直接在運費內容寫免運
![image](https://user-images.githubusercontent.com/77562017/153808523-e7d986b9-285f-444b-90be-82e3b2e93025.png)

2022-02-15 08:40 UTC, c711cat commented on src/components/Cart.vue
> +      };
1. 簡化計算運費的程式碼
https://github.com/c711cat/lemon_coffee/pull/54/commits/26a189bf927b2954679b7a38901e71c2ff5ff34f
2. 將 收件人資料的 元件加回去，調整資料互傳功能，再看哪裡需要再修正
https://github.com/c711cat/lemon_coffee/pull/54/commits/c6eff58d73a6e00498c51d1865a798949639c7fe
3. 簡化程式碼，刪除可以不必存取的內容。修改較為清楚的運費名稱。運費使用switch判讀，若傳輸來無內容暫為0
https://github.com/c711cat/lemon_coffee/pull/54/commits/41ca2ed0feb9145898344de4c17cb639b75bc70c
4. 刪除 Checkout.vue 使用 router 傳遞金額的資料( 避免使用者更動 router )，改成元件內自動計算
https://github.com/c711cat/lemon_coffee/pull/54/commits/c42741048735bbe85a62d77f3dfe77a2f0a7def7
5. 刪除 Order.vue 使用 router 傳遞金額的資料( 避免使用者更動 router )，改成元件內自動計算
https://github.com/c711cat/lemon_coffee/pull/54/commits/3c0eafbd1c6c278afce5aa035197c24dacf69a56
6. 把判斷收件地址顯示、送貨方式及付款方式的中文顯示，寫的跟 checkout 相同，之後比較快速核對
https://github.com/c711cat/lemon_coffee/pull/54/commits/2b9785f945a119ebaef058cd663e79a3fc1034bb

2022-02-15 08:41 UTC, c711cat commented on src/components/AddresseeForm.vue
> -<template>
已經加回去了喔~
過程貼在上一則的 6 項裡面，這裡就不重複貼了~

2022-02-15 08:42 UTC, c711cat commented on src/components/Checkout.vue
> +            v-if="price_details.free_shipping === 'true'"
改好了~
一起放在 6 項裡面了~

2022-02-16 06:40 UTC, kakas commented on src/components/AddresseeForm.vue
> +    shippingMethod() {
```suggestion
    emitShippingMethod() {
```

2022-02-16 06:40 UTC, kakas commented on src/components/AddresseeForm.vue
> +            @change="$emit('shipping-method', shipping_info.shipping_method)"
這邊可以使用下面寫的 method 就好
```suggestion
            @change="emitShippingMethod"
```

2022-02-16 06:40 UTC, kakas commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
應該一個條件就夠了
```suggestion
            v-if="free_shipping"
```

2022-02-16 06:40 UTC, kakas commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
```suggestion
            v-if="free_shipping"
```

2022-02-16 06:40 UTC, kakas commented on src/components/Cart.vue
> +    <AddresseeForm @shipping-method="shipping_amount"></AddresseeForm>
```suggestion
    <AddresseeForm @shipping-method="updateShippingFee"></AddresseeForm>
```

2022-02-16 06:40 UTC, kakas commented on src/components/Cart.vue
> +      payment_methods: [{ label: "貨到付款", value: "cash_on_delivery" }],
shipping_methods
payment_methods
都沒用到

2022-02-21 02:51 UTC, c711cat commented on src/components/AddresseeForm.vue
> +    shippingMethod() {
改好了~  https://github.com/c711cat/lemon_coffee/pull/54/commits/9e237aee1b287558e09e9bc37230df40cd319326

2022-02-21 03:01 UTC, c711cat commented on src/components/AddresseeForm.vue
> +            @change="$emit('shipping-method', shipping_info.shipping_method)"
改好了~
https://github.com/c711cat/lemon_coffee/pull/54/commits/e073593c2d24be62440f0070a8fb1e515dd59744

2022-02-21 03:37 UTC, c711cat commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
###  ★ v-if="free_shipping" 只有一個條件會變這樣
![image](https://user-images.githubusercontent.com/77562017/154883965-578a4b00-b403-4dee-994a-350c8d93d7de.png)

### ★ 若我把原始運費預設值改為 100，則可以只有一個條件，但會尚未選擇送貨方式時，就先出現 100 元的運費
![image](https://user-images.githubusercontent.com/77562017/154884533-df4d588f-9ad0-4629-8c5c-a1da2fe4a2ac.png)

###  ★ 綁兩個條件時，還沒選送貨方式，不會出現運費
![image](https://user-images.githubusercontent.com/77562017/154884883-7ae73194-ab22-4f1d-953a-33fcb283da83.png)
###  ★ 選送貨方式後，才會出現運費
![image](https://user-images.githubusercontent.com/77562017/154884971-9c2d7a35-4aae-4757-ace7-fe550f5c8f94.png)

建議用哪一種方式 ?

2022-02-21 06:07 UTC, c711cat commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
跟上一則相同~ https://github.com/c711cat/lemon_coffee/commit/696ce22f759d2c82268b423c389b4b0a608de6c6
將送貨方式預設值設定為 : 宅配方式，你再看看，若覺得需要改回原先的，我可以再改回去。

2022-02-21 06:18 UTC, c711cat commented on src/components/Cart.vue
> +    <AddresseeForm @shipping-method="shipping_amount"></AddresseeForm>
改好了~https://github.com/c711cat/lemon_coffee/pull/54/commits/c0d741b0383aeb6c9f5bcea653461517f7610133

2022-02-21 06:19 UTC, c711cat commented on src/components/Cart.vue
> +      payment_methods: [{ label: "貨到付款", value: "cash_on_delivery" }],
改好了
https://github.com/c711cat/lemon_coffee/pull/54/commits/8becfc457eaafe542b728010fc5cd5fb175632c9

2022-02-22 13:23 UTC, kakas commented on src/components/AddresseeForm.vue
>        }
這樣？

```suggestion
      if (localStorage.getItem("personalData")) {
        const personalData = JSON.parse(localStorage.getItem("personalData"));
        this.note = personalData.note;
        this.shipping_info = personalData.shipping_info;
      }
      this.emitShippingMethod();
```

2022-02-22 13:36 UTC, kakas commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
原本的條件讓我誤會了。

`v-if="origin_shipping_fee && free_shipping"`
會讓我理解成
「運費不是 null」且「有免運優惠」

若改成
`v-if="origin_shipping_fee > 0 && free_shipping"`
會比較好理解

2022-02-22 13:36 UTC, kakas commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
同上

2022-02-22 13:37 UTC, kakas commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
原本的條件讓我誤會了。

`v-if="origin_shipping_fee && free_shipping"`
會讓我理解成
「運費不是 null」且「有免運優惠」

若改成
`v-if="origin_shipping_fee > 0 && free_shipping"`
會比較好理解

2022-02-23 02:23 UTC, c711cat commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
改好了~https://github.com/c711cat/lemon_coffee/pull/54/commits/3b3640a9162be244987460148f9206de32d6c9c0

2022-02-23 02:23 UTC, c711cat commented on src/components/Cart.vue
> +            v-if="origin_shipping_fee && free_shipping"
同上~

2022-02-23 02:26 UTC, c711cat commented on src/components/AddresseeForm.vue
>        }
這是上面滿千免運把條件改成一個時的寫法，所以放了兩個 this.emitShippingMethod();
現在已改成一個條件，所以刪除第一個，維持原始的方式。

2022-02-23 02:42 UTC, c711cat commented on src/components/Order.vue
> +    shippingMethod() {
這裡是因為 Checkout 元件用 computed 寫，Order 元件原本使用 method 寫，
我想說這兩個元件很類似，就讓他們顯示中文的方式長的一樣，之後如果要看可以看得比較快，
所以才把原本的 Order 元件的 shippingMethodText 更改成後來的。
你的建議是 ?

2022-02-23 02:44 UTC, c711cat commented on src/components/Order.vue
> +    paymentMethod() {
這裡也是跟上一則原因相同，
上面是我更改的原因，你知道後還是建議我更改回去嗎?

2022-02-23 03:50 UTC, kakas commented on src/components/Order.vue
> +    shippingMethod() {
用 computed 或 method 寫應該不太會影響命名才對。
建議還是用 shippingMethodText 就比較好
容易分辨的命名才可以加速之後看 code 的速度

2022-02-23 03:51 UTC, kakas commented on src/components/AddresseeForm.vue
>        }
OK

2022-02-23 06:30 UTC, c711cat commented on src/components/Order.vue
> +    shippingMethod() {
改為容易分辨的命名 ( Order.vue )   https://github.com/c711cat/lemon_coffee/pull/54/commits/87e132e6432db47cc56017319ca99f3600c9edba

改為容易分辨的命名 ( Checkout.vue )  https://github.com/c711cat/lemon_coffee/pull/54/commits/46b39847f6f559f02a183336cfa882be98dc0142

2022-02-23 06:30 UTC, c711cat commented on src/components/Order.vue
> +    paymentMethod() {
同上則回覆~

2022-02-23 10:01 UTC, kakas commented on src/components/Checkout.vue
> +    },
shippingMethodText 跟 paymentMethodText 應該可以寫到 computed 裡面

2022-02-24 03:45 UTC, c711cat commented on src/components/Checkout.vue
> +    },
- 面試題目我另外寫起來

- 我不清楚你說 : shippingMethodText 跟 paymentMethodText 可以寫到 computed 裡面 的意思
- 原先他們是寫在 computed 裡面，之後因為你建議改為容易分辨的命名，我把它們改寫到 method 中，還是說 ... 只是要我更改 【名稱】 而已 【位置】不用動 ?

- 像這樣 ? https://github.com/c711cat/lemon_coffee/pull/54/commits/e492973d67f3d235678f969a112b0799e8d41f56

2022-02-24 03:52 UTC, c711cat commented
> shippingMethodText 跟 paymentMethodText 應該可以寫到 computed 裡面

- 我不清楚你說 : shippingMethodText 跟 paymentMethodText 可以寫到 computed 裡面 的意思

- 原先他們是寫在 computed 裡面，之後因為你建議改為容易分辨的命名，我把它們改寫到 method 中，還是說 ... 只是要我更改 【名稱】 而已 【位置】不用動 ?
- 像這樣 ? https://github.com/c711cat/lemon_coffee/pull/54/commits/e492973d67f3d235678f969a112b0799e8d41f56

2022-02-24 10:56 UTC, kakas commented
對！沒錯，就是這樣，讚喔

2022-02-24 10:57 UTC, merged