Feature/ 防止按鈕被連按的 【disabled + 等待轉圈 ProgressSpinner 】( disabled btn and progress spinner )
c711cat/lemon_coffee pull request #61
Opened 2022-03-24 07:58 UTC by c711cat

https://kakas-redmine.herokuapp.com/issues/1033
## 一、原因:
1. 在快速連按刪除按鈕時，畫面上有刪除該某數個品項，但又重新開啟側邊購物車時，發現某些該品項仍在，所以將打 API 出去到 API 回傳結果這段期間，讓該按鈕無法按，及讓使用者知道需要等待一下。
2. 除了【刪除】及【調整數量】按鈕，【加入購物車】及【下訂單】按鈕，單純為了避免連按而增設的功能。

## 二、有增加效果按鈕 :
- Router   /products/:id ，元件    ProductDetail.vue  【加入購物車】按鈕
- 側邊購物車 ，元件    CartSidebar.vue  【垃圾桶】按鈕、調整購買數量的【InputNumber】
- Router   /cart ，元件   Cart.vue  【垃圾桶】按鈕、調整購買數量的【InputNumber】
- Router    /checkout ，元件    Checkout.vue  【下訂單】按鈕

### ★ Router   /products/:id ，元件    ProductDetail.vue  【加入購物車】按鈕
![image](https://user-images.githubusercontent.com/77562017/159867411-e157f23e-d931-4779-b55e-50bcc6df2be9.png)
### ★ 側邊購物車 ，元件    CartSidebar.vue  【垃圾桶】按鈕、調整購買數量的【InputNumber】
![image](https://user-images.githubusercontent.com/77562017/159868147-e6dad666-fd54-4296-a419-ebaa129bae2a.png)
![image](https://user-images.githubusercontent.com/77562017/159867969-a210c891-3762-4383-9b88-9597ff389955.png)
### ★ Router   /cart ，元件   Cart.vue  【垃圾桶】按鈕、調整購買數量的【InputNumber】
![image](https://user-images.githubusercontent.com/77562017/159868734-8a953fd2-7aa6-4773-b0e9-088980f8e724.png)
![image](https://user-images.githubusercontent.com/77562017/159868471-660ece7b-5737-4d64-904d-b68294ad6ed4.png)
### ★ Router    /checkout ，元件    Checkout.vue  【下訂單】按鈕
![image](https://user-images.githubusercontent.com/77562017/159869177-4260c083-efe1-4f43-81fa-8f14ffff77f0.png)

2022-04-08 10:33 UTC, kakas commented on src/components/Checkout.vue
> +          this.btnIsLoading = false;
nice

2022-04-08 12:24 UTC, kakas requested changes

2022-04-08 12:24 UTC, kakas commented on src/components/CartSidebar.vue
> +          v-if="loadingItem === index + item.product_name"
看不懂
為什麼要用 index + item.product_name 判斷？
還是你可以改成比較直覺的寫法？

2022-04-09 05:47 UTC, c711cat commented on src/components/CartSidebar.vue
> +          v-if="loadingItem === index + item.product_name"
- 因為目前沒有自動加總【 同品項 同包裝 同磨粉狀態】 的功能，所以才會寫 index 方便區分，當要刪除或變更數量才不會搞混

- 如果我分次各加了 1 次【 耶家雪菲 半磅 原豆 數量 1 】會長這樣 ↓

![image](https://user-images.githubusercontent.com/77562017/162558306-3d0ee0d6-8d35-42c3-8b0f-66e19ccf14a0.png)

2022-04-10 05:00 UTC, kakas commented on src/components/CartSidebar.vue
> +          v-if="loadingItem === index + item.product_name"
不然就先醬吧

2022-04-10 05:01 UTC, kakas commented
有 loading 的狀態感覺體驗好很多
讚讚

2022-04-10 05:01 UTC, kakas approved these changes

2022-04-10 05:01 UTC, merged